import { RequiredDataFromCollectionSlug } from 'payload'

export const comandaForm: RequiredDataFromCollectionSlug<'forms'> = {
  title: 'Formular Comandă',
  confirmationType: 'message',
  confirmationMessage: {
    root: {
      type: 'root',
      children: [
        {
          type: 'heading',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Mulțumim pentru comandă!',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          tag: 'h2',
          version: 1,
        },
        {
          type: 'paragraph',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Te vom contacta în cel mai scurt timp pentru finalizarea comenzii.',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          textFormat: 0,
          version: 1,
        },
      ],
      direction: 'ltr',
      format: '',
      indent: 0,
      version: 1,
    },
  },
  emails: [
    // Email 1: Către PROPRIETAR (tu)
    {
      emailFrom: '"Transilvania Fitness" <onboarding@resend.dev>', // Pentru test; în producție: noreply@domeniul-verificat.ro
      emailTo: 'mihaialex_barascu@yahoo.com', // Email-ul tău fix
      replyTo: '{{email}}', // Reply merge direct la client
      subject: '🔔 [{{tip}}] Comandă nouă: {{optiune}} de la {{prenume}} {{nume}}',
      message: {
        root: {
          type: 'root',
          children: [
            {
              type: 'heading',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Comandă nouă primită!',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h2',
              version: 1,
            },
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 1, // bold
                  mode: 'normal',
                  style: '',
                  text: 'Tip: ',
                  version: 1,
                },
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: '{{tip}}',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 1,
                  mode: 'normal',
                  style: '',
                  text: 'Opțiune: ',
                  version: 1,
                },
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: '{{optiune}}',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 1,
                  mode: 'normal',
                  style: '',
                  text: 'Prenume: ',
                  version: 1,
                },
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: '{{prenume}}',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 1,
                  mode: 'normal',
                  style: '',
                  text: 'Nume: ',
                  version: 1,
                },
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: '{{nume}}',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 1,
                  mode: 'normal',
                  style: '',
                  text: 'Email: ',
                  version: 1,
                },
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: '{{email}}',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 1,
                  mode: 'normal',
                  style: '',
                  text: 'Telefon: ',
                  version: 1,
                },
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: '{{telefon}}',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 1,
                  mode: 'normal',
                  style: '',
                  text: 'Mesaj: ',
                  version: 1,
                },
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: '{{mesaj}}',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
    },
    // Email 2: Către CLIENT (confirmare)
    {
      emailFrom: '"Transilvania Fitness" <onboarding@resend.dev>', // Pentru test; în producție: noreply@domeniul-verificat.ro
      emailTo: '{{email}}',
      subject: 'Confirmare comandă - {{optiune}}',
      message: {
        root: {
          type: 'root',
          children: [
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Salut {{prenume}}!',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Mulțumim pentru interesul tău în {{optiune}}! Te vom contacta în curând pentru detalii.',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
    },
  ],
  submitButtonLabel: 'Trimite Comanda',
  fields: [
    // Câmp tip - pre-completat din URL (ex: ?tip=abonament)
    {
      name: 'tip',
      blockName: 'tip',
      blockType: 'select',
      label: 'Tip Comandă',
      required: true,
      width: 50,
      defaultValue: 'abonament',
      options: [
        { label: 'Abonament', value: 'abonament' },
        { label: 'Antrenor Personal', value: 'antrenor' },
        { label: 'Clasă Fitness', value: 'clasa' },
      ],
    },
    // Câmp optiune - pre-completat din URL (ex: ?optiune=Premium)
    {
      name: 'optiune',
      blockName: 'optiune',
      blockType: 'text',
      label: 'Opțiune Selectată',
      required: true,
      width: 50,
    },
    // Câmpuri contact
    {
      name: 'prenume',
      blockName: 'prenume',
      blockType: 'text',
      label: 'Prenume',
      required: true,
      width: 50,
    },
    {
      name: 'nume',
      blockName: 'nume',
      blockType: 'text',
      label: 'Nume',
      required: true,
      width: 50,
    },
    {
      name: 'email',
      blockName: 'email',
      blockType: 'email',
      label: 'Email',
      required: true,
      width: 50,
    },
    {
      name: 'telefon',
      blockName: 'telefon',
      blockType: 'text',
      label: 'Telefon',
      required: true,
      width: 50,
    },
    // Mesaj opțional
    {
      name: 'mesaj',
      blockName: 'mesaj',
      blockType: 'textarea',
      label: 'Mesaj (opțional)',
      required: false,
      width: 100,
    },
  ],
  redirect: undefined,
}
